### ISSUE TITLE
R25 not available (error code provided)

### ISSUE THREAD

**Issue by XTTGO** [kapellan2000/Cinema#1]
Traceback (most recent call last):
  File "C:\Users\****E\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 59, in Execute
    self._file_save_com()
  File "C:\Users\****\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 43, in _file_save_com
    PrismInit.pcore.saveWithComment()
AttributeError: module 'PrismInit' has no attribute 'pcore'
Traceback (most recent call last):
  File "C:\Users\****\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 57, in Execute
    self._file_save()
  File "C:\Users\****\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 40, in _file_save
    PrismInit.pcore.saveScene()
AttributeError: module 'PrismInit' has no attribute 'pcore'
Traceback (most recent call last):
  File "C:\Users\****\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 65, in Execute
    self._settings()
  File "C:\Users\****\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 53, in _settings
    PrismInit.pcore.prismSettings()
AttributeError: module 'PrismInit' has no attribute 'pcore'
Traceback (most recent call last):
  File "D:\Prism\Scripts\PrismCore.py", line 92, in <module>
    from PySide2.QtCore import *
  File "D:\Prism\PythonLibs\Python37\PySide\PySide2\__init__.py", line 51, in <module>
    _setupQtDirectories()
  File "D:\Prism\PythonLibs\Python37\PySide\PySide2\__init__.py", line 21, in _setupQtDirectories
    import shiboken2
  File "D:\Prism\PythonLibs\Python37\PySide\shiboken2\__init__.py", line 27, in <module>
    from .shiboken2 import *
ModuleNotFoundError: No module named 'shiboken2.shiboken2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Prism\Scripts\PrismCore.py", line 100, in <module>
    from PySide.QtCore import *
ModuleNotFoundError: No module named 'PySide.QtCore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Prism\Scripts\PrismCore.py", line 105, in <module>
    from PySide2.QtCore import *
  File "D:\Prism\PythonLibs\Python37\PySide\PySide2\__init__.py", line 51, in <module>
    _setupQtDirectories()
  File "D:\Prism\PythonLibs\Python37\PySide\PySide2\__init__.py", line 21, in _setupQtDirectories
    import shiboken2
  File "D:\Prism\PythonLibs\Python37\PySide\shiboken2\__init__.py", line 27, in <module>
    from .shiboken2 import *
ModuleNotFoundError: No module named 'shiboken2.shiboken2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\****E\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 61, in Execute
    self._browser()
  File "C:\Users\****\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 46, in _browser
    PrismInit.createPrismCore()
  File "D:/Prism\Plugins\Apps\Cinema\Integration\python3.7libs\PrismInit.py", line 39, in createPrismCore
    pcore = prismInit()
  File "D:/Prism\Plugins\Apps\Cinema\Integration\python3.7libs\PrismInit.py", line 26, in prismInit
    import PrismCore
  File "D:\Prism\Scripts\PrismCore.py", line 109, in <module>
    from PySide.QtCore import *
ModuleNotFoundError: No module named 'PySide.QtCore'
Traceback (most recent call last):
  File "C:\Users\****\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 63, in Execute
    self._state()
  File "C:\Users\****\AppData\Roaming\Maxon\Cinema 4D R25_DFE6F0E3\plugins\prism\pythonrc.pyp", line 50, in _state
    PrismInit.pcore.stateManager()
AttributeError: module 'PrismInit' has no attribute 'pcore'
>>>

**Comment by XTTGO** [comment]
R23 ：![Snipaste_2021-11-20_15-35-26](https://user-images.githubusercontent.com/38094114/142718604-bfa58de7-65b5-493c-9e73-0821ad749a2c.png)

**Comment by kapellan2000** [comment]
some kind of incompatibility with R25, next week I will try to fix it. We are still using R23

**Comment by XTTGO** [comment]
> 某种与 R25 不相容， 下周我会尝试修复它。我们仍在使用 R23

Thank you for your reply, the screenshot above me is the pop-up prompt when I use the prism function in R23.

**Comment by kapellan2000** [comment]
The problem was in the installation script. I fixed it yesterday. Redownload all or just install.cmd

**Comment by XTTGO** [comment]
Ok, thank you very much for your patience. r25 is much faster than r23 in terms of process using xref. (I'm using RS rendering process, udim mapping is very slow to load once more, I don't know if octane is the same.) I'm looking forward to updating the R25 version, thanks again for your selfless sharing, I'm also learning python as soon as possible to improve the process with you.

**Comment by kapellan2000** [comment]
Solved compatibility issue with R24 and R25.

**Comment by XTTGO** [comment]
Nice~ thanks for you

**Comment by XTTGO** [comment]
emmmm, something else has happened.
The script does not seem to work, I just downloaded your latest
![Snipaste_2021-11-30_23-46-19](https://user-images.githubusercontent.com/38094114/144079903-93a15fd6-0f14-427a-a0b5-0958800ace81.png)

**Comment by kapellan2000** [comment]
try running as administrator
![image](https://user-images.githubusercontent.com/21256398/144080283-3359af56-795a-42ef-8445-a538f48611c7.png)

**Comment by XTTGO** [comment]
I just tried it out myself, it seems that the script needs to be run under C drive to be effective, I put it on E drive before

**Comment by XTTGO** [comment]
![Snipaste_2021-12-01_00-09-40](https://user-images.githubusercontent.com/38094114/144084073-ba5dee1f-a2cc-401c-a2f4-6044df11b2a0.png)
I dont  no why
Am I missing some system component or something?

**Comment by kapellan2000** [comment]
try copying python3.dll from archive Cinema-main.zip \ Cinema-main \ Integration \ python3.9libs to C: \ Program Files \ Maxon Cinema 4D R25 \ resource \ modules \ python \ libs \ python39.win64.framework
![image](https://user-images.githubusercontent.com/21256398/144086029-6ad0695b-a870-4888-9cc8-4c3c685fbb08.png)

**Comment by XTTGO** [comment]
![Snipaste_2021-12-01_00-27-06](https://user-images.githubusercontent.com/38094114/144087907-78f37af0-806e-4d7e-96c3-40f66f409ed6.png)
I tried R23 by the way and it also reported an error. I've managed the prism tray
Could it be my folder naming
I'm not a folder like Maxon Cinema 4D R25. I am removing the Maxon
But strangely enough, your first version at the beginning worked fine for me

**Comment by XTTGO** [comment]
[> 
](https://github.com/kapellan2000/Cinema/issues/1#issuecomment-982794316)
Failure

**Comment by kapellan2000** [comment]
> 
(Cinema R23) I have fixed this error. Now everything should work at 23. You need to redownload the archive.
(Cinema R25) Have you tried copying python3.dll via explorer to python39.win64.framework?

**Comment by XTTGO** [comment]
（Cinema R25）你有没有试过通过资源管理器将python3.dll复制到python39.win64.framework？

I have tried and the above mentioned failure is about this

**Comment by XTTGO** [comment]
> 

yes.I have tried and the above mentioned failure is about this
![Snipaste_2021-12-01_02-08-19](https://user-images.githubusercontent.com/38094114/144103461-22d9f1cc-4c38-4516-9a3e-60fe7d4b4b3f.png)

**Comment by XTTGO** [comment]
![Uploading Snipaste_2021-12-01_02-08-19.png…]()

**Comment by kapellan2000** [comment]
Most likely the problem is in the libraries that are installed in our studio. I added the missing files to the repository. Would you mind checking? thanks

**Comment by XTTGO** [comment]
Yes, I can cooperate with you to test together, how do I need to cooperate with you?

**Comment by XTTGO** [comment]
ok, use your installation script to follow your installation method again, download the latest package file, and it works perfectly in R23,R25.
