### ISSUE TITLE
StateManager - Publish Error - Submit to Deadline

### ISSUE THREAD

**Issue by StefanKirste** [kapellan2000/Cinema#11]
Want to publish trough deadline or playblast dont work:

19/03/24 13:28:04 ERROR - Prism_Deadline_Functions

Core: v2.0.3
App plugin: Cinema v2.0.0.beta17.11
Plugin: Deadline v2.0.3

  File "//qumulo/Pipeline\Pipeline/PRISM/PSL/Prism_v2.0.3\Scripts\PrismUtils\Decorators.py", line 54, in func_wrapper
    return func(*args, **kwargs)
  File "\\qumulo\Pipeline\Pipeline\PRISM\PSL\Prism_v2.0.3\Scripts\ProjectScripts\StateManager.py", line 1954, in publish
    exResult = curUi.executeState(parent=self)
  File "//qumulo/Pipeline\Pipeline/PRISM/PSL/Prism_v2.0.3\Scripts\PrismUtils\Decorators.py", line 54, in func_wrapper
    return func(*args, **kwargs)
  File "\\qumulo\Pipeline\Pipeline\PRISM\PSL\Prism_v2.0.3\Scripts\ProjectScripts\StateManagerNodes\default_ImageRender.py", line 1181, in executeState
    result = plugin.sm_render_submitJob(
  File "//qumulo/Pipeline\Pipeline/PRISM/PSL/Prism_v2.0.3\Scripts\PrismUtils\Decorators.py", line 54, in func_wrapper
    return func(*args, **kwargs)
  File "\\qumulo\Pipeline\Pipeline\PRISM\PSL\Plugins\Deadline\Scripts\Prism_Deadline_Functions.py", line 1344, in sm_render_submitJob
    result = self.deadlineSubmitJob(jobInfos, pluginInfos, arguments)
  File "//qumulo/Pipeline\Pipeline/PRISM/PSL/Prism_v2.0.3\Scripts\PrismUtils\Decorators.py", line 89, in func_wrapper
    "".join(traceback.format_stack()),

Traceback (most recent call last):
  File "//qumulo/Pipeline\Pipeline/PRISM/PSL/Prism_v2.0.3\Scripts\PrismUtils\Decorators.py", line 54, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "\\qumulo\Pipeline\Pipeline\PRISM\PSL\Plugins\Deadline\Scripts\Prism_Deadline_Functions.py", line 2817, in deadlineSubmitJob
    with open(arguments[0], "w") as fileHandle:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by StefanKirste** [comment]
after added 2024.3.2 support the error still persist
