### ISSUE TITLE
Error reported when creating new version from autobackup through Prism ontology - Cinema

### ISSUE THREAD

**Issue by XTTGO** [kapellan2000/Cinema#6]
![image](https://github.com/kapellan2000/Cinema/assets/38094114/999fa803-b466-4267-ac19-e18182d7fdf9)

```
18/09/23 18:30:35 ERROR - Prism_Cinema_externalAccess_Functions

Core: v2.0.0.beta17.10
App plugin: Standalone v2.0.0.beta2
Plugin: Cinema v2.0.0.beta15

  File "D:\Prism2\Scripts\PrismTray.py", line 427, in <module>
    sys.exit(qApp.exec_())
  File "D:\Prism2\Scripts\PrismUtils\Decorators.py", line 53, in func_wrapper
    return func(*args, **kwargs)
  File "D:\Prism2\Scripts\ProjectScripts\SceneBrowser.py", line 881, in rclItemView
    self.openScenefileContextMenu()
  File "D:\Prism2\Scripts\PrismUtils\Decorators.py", line 53, in func_wrapper
    return func(*args, **kwargs)
  File "D:\Prism2\Scripts\ProjectScripts\SceneBrowser.py", line 1030, in openScenefileContextMenu
    rcmenu.exec_(QCursor.pos())
  File "D:\Prism2\Scripts\ProjectScripts\SceneBrowser.py", line 947, in <lambda>
    autobAct.triggered.connect(lambda y=None, x=pluginName: self.autoback(x))
  File "D:\Prism2\Scripts\PrismUtils\Decorators.py", line 53, in func_wrapper
    return func(*args, **kwargs)
  File "D:\Prism2\Scripts\ProjectScripts\SceneBrowser.py", line 1143, in autoback
    filepath = self.core.entities.createVersionFromAutoBackupDlg(
  File "D:\Prism2\Scripts\PrismUtils\Decorators.py", line 53, in func_wrapper
    return func(*args, **kwargs)
  File "D:\Prism2\Scripts\PrismUtils\ProjectEntities.py", line 1793, in createVersionFromAutoBackupDlg
    result = self.getAutobackPath(prog, entity, department, task)
  File "D:\Prism2\Scripts\PrismUtils\Decorators.py", line 53, in func_wrapper
    return func(*args, **kwargs)
  File "D:\Prism2\Scripts\PrismUtils\ProjectEntities.py", line 1767, in getAutobackPath
    autobackpath, fileStr = i.getAutobackPath(self)
  File "D:\Prism2\Scripts\PrismUtils\Decorators.py", line 88, in func_wrapper
    "".join(traceback.format_stack()),


Traceback (most recent call last):
  File "D:\Prism2\Scripts\PrismUtils\Decorators.py", line 53, in func_wrapper
    return func(*args, **kwargs)
TypeError: getAutobackPath() missing 1 required positional argument: 'tab'
```

**Comment by kapellan2000** [comment]
this problem has been fixed. Update the script
