### ISSUE TITLE
'PrismInit' has no attribute 'pcore' | Cinema 2024.1.0

### ISSUE THREAD

**Issue by AendrewHD** [kapellan2000/Cinema#7]
When i try to access the prism plugin in Cinema 2024.1.0 i get the following error in the console:

`Traceback (most recent call last):
  File "C:\Users\aaulb\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\plugins\prism\pythonrc.pyp", line 65, in Execute
  File "C:\Users\aaulb\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\plugins\prism\pythonrc.pyp", line 53, in _settings
AttributeError:module 'PrismInit' has no attribute 'pcore'`

Thanks for your help in advance

**Comment by kapellan2000** [comment]
Hello, I have made some changes, please try downloading again.
If that doesn't help, please let me know your exact Prism version and whether Prism is installed in the default directory.

**Comment by AendrewHD** [comment]
Thanks. I now get the following Message:

`No Qt bindings could be found
Traceback (most recent call last):
  File "C:\Users\aaulb\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\plugins\Connecter plugin\DSmessage.pypv", line 1715, in PluginMessage
  File "C:\Users\aaulb\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\plugins\Connecter plugin\DSmessage.pypv", line 1722, in AddToMenu
AttributeError:module 'c4d' has no attribute 'MENURESOURCE_SEPERATOR'
Traceback (most recent call last):
  File "C:\Users\aaulb\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\plugins\Connecter plugin\DSmessage.pypv", line 1715, in PluginMessage
  File "C:\Users\aaulb\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\plugins\Connecter plugin\DSmessage.pypv", line 1722, in AddToMenu
AttributeError:module 'c4d' has no attribute 'MENURESOURCE_SEPERATOR'
Traceback (most recent call last):
  File "C:\Users\aaulb\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\plugins\prism\pythonrc.pyp", line 65, in Execute
  File "C:\Users\aaulb\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\plugins\prism\pythonrc.pyp", line 53, in _settings
NameError:name 'PrismInit' is not defined. Did you mean: 'prismRoot'?`

I installed Prism v2.0.0, the release Version, to the main Directory. Also installed the Plugin again after your update. The plugins are linked to the Appdata Folder of Cinema.

**Comment by kapellan2000** [comment]
1 Try to allocate the plugin from the main folder.
2 Restart Prism.
3 Copy it to the folder C:\ProgramData\Prism2\plugins\Cinema\
4 Add the plugin as shown in the picture.

![Screenshot 2023-11-09 at 10 55 26](https://github.com/kapellan2000/Cinema/assets/21256398/203238c4-0e23-46d9-90e7-d87d7f5f7185)
5 Remove and re-add the integration to your Cinema 4D version.

**Comment by kapellan2000** [comment]
If it helps, I will add the ability to launch the plugin from different locations.

**Comment by AendrewHD** [comment]
![Screenshot_85](https://github.com/kapellan2000/Cinema/assets/61575959/ee2d3a13-4d25-4c04-a77c-22eddbd6f68b)

I Have it already configured as you pictured. Cinema is also installed to the default location. Anything else it could be?

**Comment by kapellan2000** [comment]
Based on the log, are you using Vray? Is that correct? If Vray is installed in Cinema 4D, the plugin doesn't work. I'm trying to solve this issue.

**Comment by AendrewHD** [comment]
ah yes that was it. We were using v-ray for a while but went back to redshift. Didnt think it being installed would be a problem. Thank you so much!!
